version: "3"

services:
    nginx:
        build: ./docker/nginx
        container_name: nginx.docker
        volumes:
            - ".:/var/www/html/vale-express"
            - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./docker/nginx/conf.d:/etc/nginx/conf.d"
            - "./docker/logs/nginx:/var/log/nginx"
        ports:
            - "80:80"
            - "443:443"
        restart: always
        depends_on:
            - php
            - mysqldb
        links:
            - php

    php:
        build: ./docker/php
        container_name: php.docker
        restart: always
        volumes:
            - "./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - ".:/var/www/html/vale-express"
        expose:
            - "9000"
        ports:
            - "9000:9000"

    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin.docker
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${DB_HOST}
        restart: always
        depends_on:
            - mysqldb

    mysqldb:
        image: mysql:5.7
        container_name: mysql.docker
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - "./docker/mysql/lib:/var/lib/mysql"
            - "./docker/mysql/conf.d:/etc/mysql/conf.d"